### ISSUE TITLE
further development

### ISSUE THREAD

**Issue by ghost** [vhpoet/ripple-php#1]
please improve the ripple-php library. i may need it in the next days/weeks. are there any plans? i will commit new code when i am using the lib. thx

**Comment by vhpoet** [comment]
Hey, I want to improve it, but I don't have the time :(

**Comment by hopeseekr** [comment]
That's the story of my life, brother!

**Comment by hopeseekr** [comment]
Based on the zero-comment closure, and that this project hasn't been updated in over 5 years...

You abandoned it, huh? Time to fork!!
